# Generated by Django 3.2.8 on 2021-11-09 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Forename')),
                ('last_name', models.CharField(max_length=35, verbose_name='Surname')),
                ('address_1', models.CharField(max_length=128, verbose_name='Address line 1')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name='Address line 2')),
                ('postcode', models.CharField(max_length=12, verbose_name='Postcode')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('email', models.EmailField(blank=True, max_length=320, verbose_name='Contact Email')),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
            ],
        ),
    ]
