# Generated by Django 3.2.8 on 2021-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseclass'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courses.CourseClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=None, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='funding',
            field=models.CharField(choices=[('JSA', 'Job Seekers Allowance'), ('ESA', 'Employability Support Allowance'), ('UC', 'Universal Credit'), ('ISA', 'Income Support Allowance'), ('CTB', 'Council Tax Benefit'), ('HB', 'Housing Benefit'), ('WTC', 'Working Tax Credit'), ('PC', 'Pension Credit'), ('NO', 'Not in reciept of benefits')], default='NO', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='ia_done',
            field=models.BooleanField(default=False, verbose_name='Initial Assessment Completed'),
        ),
        migrations.AddField(
            model_name='student',
            name='ia_sent',
            field=models.BooleanField(default=False, verbose_name='Initial Assessment Sent'),
        ),
        migrations.AddField(
            model_name='student',
            name='int_courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('REF', 'Referral'), ('STD', 'Enrolled'), ('ALM', 'Alumni'), ('NLI', 'No Longer Interested')], default='REF', max_length=3),
        ),
    ]
