# Generated by Django 3.2.8 on 2021-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrol_num',
            field=models.CharField(blank=True, max_length=8, verbose_name='Student Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrol_url',
            field=models.URLField(blank=True, verbose_name='Link to myPortal Page'),
        ),
    ]
