# Generated by Django 3.2.8 on 2021-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseclass'),
        ('students', '0004_auto_20211116_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='courses.CourseClass'),
        ),
    ]
