# Generated by Django 3.2.8 on 2021-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211116_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrol_num',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrol_url',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('REF', 'Referral'), ('STD', 'Enrolled'), ('ALM', 'Alumni'), ('PRG', 'Progression'), ('NLI', 'No Longer Interested')], default='REF', max_length=3),
        ),
    ]
