# Generated by Django 3.2.8 on 2022-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=70, verbose_name='Full Name (Optional)')),
                ('email', models.EmailField(max_length=320, verbose_name='Email Address')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
