# Generated by Django 3.2.8 on 2021-11-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20211117_1248'),
        ('courses', '0003_courseclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='schools.school'),
        ),
    ]
