# Generated by Django 3.2.8 on 2021-11-17 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
