# Generated by Django 3.2.8 on 2021-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20211117_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='event', max_length=254),
            preserve_default=False,
        ),
    ]
